[package]
name = "qrust"
version = "0.1.0"
edition = "2021"

[features]
default = ["wasm"]
wasm = ["dep:wasm-bindgen", "dep:wee_alloc"]
text = []

[lib]
crate-type = ["cdylib", "rlib"]

# [target.'cfg(target_arch = "wasm32")'.dependencies]
[dependencies]
wasm-bindgen = { version = "0.2.92", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[profile.release]
lto = true
